yarnPath: "../../.yarn/releases/yarn-3.6.3.cjs"
cacheFolder: "../../.yarn/cache"
nodeLinker: node-modules
# let yalc update the yarn lockfile in CI
enableImmutableInstalls: false
# nmHoistingLimits: workspaces
