name: Tests

on:
  pull_request: ~
  push:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres:16.0
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: medusa-docker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i @medusajs/medusa-cli -g

      - name: Install dependencies
        run: npm i yalc -g

      - name: Install dependencies
        run: yarn install

      - name: Install dependencies
        run: cd medusa-plugin-bundles && yarn install && yalc publish && cd ../dev/medusa && yalc add medusa-plugin-bundles && yarn install

      - name: Run migrations
        run: cd dev/medusa && medusa migrations run

      - name: Seed the database
        run: cd dev/medusa && yarn run seed:medusa-plugin-bundles

      - name: background-action
        uses: JarvusInnovations/background-action@v1.0.3
        with:
          run: cd dev/medusa && yarn run start
          wait-on: http://localhost:9000/store/bundles/bundle_coffeemugs01
          wait-for: 1m

      - name: Install test dependencies
        run: cd tests && yarn install

      - name: Run tests
        run: cd tests && yarn run test
